name: rts_isometric_game
description: A pixel art isometric RTS game built with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  google_sign_in: ^6.2.1
  supabase_flutter: ^2.8.3
  provider: ^6.1.2
  flame: ^1.37.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/main_menu_bg.png
